import csv
import re
from multiprocessing.resource_sharer import stop

import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
from wordcloud import WordCloud

file = open("../../Documents/data/" + input("File: ") + ".csv")

type(file)

csvreader = csv.reader(file)

rows = []
text = ""
for row in csvreader:
  rows.append(row)
  print(row[0])
  for sentence in row:
    text = text + sentence + " "

text += '\n'
print(rows[0])


file.close()

print(text)
# Levanto texto



nltk.download('stopwords')

stopwords = set(stopwords.words('spanish')) 

shortword = re.compile(r'\W*\b\w{1,3}\b')
text=shortword.sub('', text)

stopwords.add("Uruguay")
stopwords.add("Brasil")
stopwords.add("Problema")
stopwords.add("PROBLEMA")
stopwords.add("PROBLEMAS")
stopwords.add("Precio")
stopwords.add("ENVIO")
stopwords.add("INTERIOR")
stopwords.add("ARGENTINOS")
stopwords.add("REPUBLICA ARGENTINA")
stopwords.add("ayer")
stopwords.add("pagina")
stopwords.add("REPUBLICA")
stopwords.add("ARGENTINA")
stopwords.add("Aire")
stopwords.add("TOQUE")
stopwords.add("ATENCION")
stopwords.add("Recargo")
stopwords.add("República")
stopwords.add("Envio")
stopwords.add("Buenos")
stopwords.add("Aires")
stopwords.add("dijo")
stopwords.add("opcionales")
stopwords.add("OPCIONALES")
stopwords.add("índice")
stopwords.add("OPCIONAL")
stopwords.add("SOLUCION")
stopwords.add("Capital")
stopwords.add("envío")
stopwords.add("Clarín")
stopwords.add("impresión")
stopwords.add("Precios")
stopwords.add("Federal")
stopwords.add("delo")
stopwords.add("DELOS")
stopwords.add("COMPRA")
stopwords.add("digital")
stopwords.add("Paraguay")
stopwords.add("Ademá")
stopwords.add("INDICE")
stopwords.add("SOCIEDAD")
stopwords.add("página")
stopwords.add("despué")
stopwords.add("dela")
stopwords.add("PARALA")
stopwords.add("CLARIN")
stopwords.add("ESPECTACULO")
stopwords.add("ClarínX")
stopwords.add("ESPECTACULOS")
stopwords.add("años")
stopwords.add("Además")
stopwords.add("enla")
stopwords.add("ahora")
stopwords.add("PAGS")
stopwords.add("LVIII")
stopwords.add("DEPORTIVO")
stopwords.add("FRASE")
stopwords.add("Pacs")
stopwords.add("GRATIS")
stopwords.add("LXIV")
stopwords.add("Plata")
stopwords.add("Provincia")
stopwords.add("FRASEDELDIA")
stopwords.add("LXVIN")
stopwords.add("LXVI")
stopwords.add("LXVII")
stopwords.add("LXVIII")
stopwords.add("LXIX")
stopwords.add("LXXN")
stopwords.add("LXXIN")
stopwords.add("LXXII")
stopwords.add("LXXIIN")
stopwords.add("LXXI")
stopwords.add("IMPRESION")
stopwords.add("atención")
stopwords.add("LXXIII")
stopwords.add("LXXIV")
stopwords.add("días")
stopwords.add("meno")
stopwords.add("después")
stopwords.add("LXXV")
stopwords.add("sólo")
stopwords.add("LXXVIN")
stopwords.add("Tema")
stopwords.add("solución")
stopwords.add("PAGINA")
stopwords.add("PAGINAS")
stopwords.add("CUARENTA")
stopwords.add("INFORMACION")
stopwords.add("Edición")
stopwords.add("TRES")
stopwords.add("CUATRO")
stopwords.add("SUPL")
stopwords.add("Diario")
stopwords.add("mañana")
stopwords.add("Gran")
stopwords.add("TREINTA")
stopwords.add("CINCO")
stopwords.add("ejemplar")
stopwords.add("SEIS")
stopwords.add("SIETE")
stopwords.add("OCHO")
stopwords.add("NUEVE")
stopwords.add("páginas")
stopwords.add("aérea")
stopwords.add("país")
stopwords.add("tapa")
stopwords.add("Chile")
stopwords.add("HECHOS")
stopwords.add("IMPORTANTES")
stopwords.add("PANORAMA")
stopwords.add("Radiofoto")
stopwords.add("Información")
stopwords.add("NACIONAL")
stopwords.add("DIEZ")
stopwords.add("EDITORIAL")
stopwords.add("SECCIONE")
stopwords.add("SECCIONES")
stopwords.add("Inform")
stopwords.add("ONCE")
stopwords.add("DOCE")
stopwords.add("Catorce")
stopwords.add("CATORCE")
stopwords.add("TRECE")
stopwords.add("págino")

print(stopwords)
word_cloud = WordCloud(stopwords=stopwords).generate(text)
plt.imshow(word_cloud, interpolation='bilinear')
plt.axis("off")
plt.show()
